
MathJax.Hub.Register.StartupHook('TeX Jax Ready', function () {
  MathJax.InputJax.TeX.Definitions.Add({
    macros: {
      Brack: ['Macro', '\\left[ #1 \\right]'],
      Paren: ['Macro', '\\left( #1 \\right)'],
      Brace: ['Macro', '\\left\\{#1\\right\\}'],
      calA: ['Macro', '\\mathcal{A}'],
      calB: ['Macro', '\\mathcal{B}'],
      calC: ['Macro', '\\mathcal{C}'],
      calD: ['Macro', '\\mathcal{D}'],
      calE: ['Macro', '\\mathcal{E}'],
      calF: ['Macro', '\\mathcal{F}'],
      calG: ['Macro', '\\mathcal{G}'],
      calH: ['Macro', '\\mathcal{H}'],
      calI: ['Macro', '\\mathcal{I}'],
      calJ: ['Macro', '\\mathcal{J}'],
      calK: ['Macro', '\\mathcal{K}'],
      calL: ['Macro', '\\mathcal{L}'],
      calM: ['Macro', '\\mathcal{M}'],
      calN: ['Macro', '\\mathcal{N}'],
      calO: ['Macro', '\\mathcal{O}'],
      calP: ['Macro', '\\mathcal{P}'],
      calQ: ['Macro', '\\mathcal{Q}'],
      calR: ['Macro', '\\mathcal{R}'],
      calS: ['Macro', '\\mathcal{S}'],
      calT: ['Macro', '\\mathcal{T}'],
      calU: ['Macro', '\\mathcal{U}'],
      calV: ['Macro', '\\mathcal{V}'],
      calW: ['Macro', '\\mathcal{W}'],
      calX: ['Macro', '\\mathcal{X}'],
      calY: ['Macro', '\\mathcal{Y}'],
      calZ: ['Macro', '\\mathcal{Z}'],
      bfA: ['Macro', '\\mathbf{A}'],
      bfB: ['Macro', '\\mathbf{B}'],
      bfC: ['Macro', '\\mathbf{C}'],
      bfD: ['Macro', '\\mathbf{D}'],
      bfE: ['Macro', '\\mathbf{E}'],
      bfF: ['Macro', '\\mathbf{F}'],
      bfG: ['Macro', '\\mathbf{G}'],
      bfH: ['Macro', '\\mathbf{H}'],
      bfI: ['Macro', '\\mathbf{I}'],
      bfJ: ['Macro', '\\mathbf{J}'],
      bfK: ['Macro', '\\mathbf{K}'],
      bfL: ['Macro', '\\mathbf{L}'],
      bfM: ['Macro', '\\mathbf{M}'],
      bfN: ['Macro', '\\mathbf{N}'],
      bfO: ['Macro', '\\mathbf{O}'],
      bfP: ['Macro', '\\mathbf{P}'],
      bfQ: ['Macro', '\\mathbf{Q}'],
      bfR: ['Macro', '\\mathbf{R}'],
      bfS: ['Macro', '\\mathbf{S}'],
      bfT: ['Macro', '\\mathbf{T}'],
      bfU: ['Macro', '\\mathbf{U}'],
      bfV: ['Macro', '\\mathbf{V}'],
      bfW: ['Macro', '\\mathbf{W}'],
      bfX: ['Macro', '\\mathbf{X}'],
      bfY: ['Macro', '\\mathbf{Y}'],
      bfZ: ['Macro', '\\mathbf{Z}'],
      bfa: ['Macro', '\\mathbf{a}'],
      bfb: ['Macro', '\\mathbf{b}'],
      bfc: ['Macro', '\\mathbf{c}'],
      bfd: ['Macro', '\\mathbf{d}'],
      bfe: ['Macro', '\\mathbf{e}'],
      bff: ['Macro', '\\mathbf{f}'],
      bfg: ['Macro', '\\mathbf{g}'],
      bfh: ['Macro', '\\mathbf{h}'],
      bfi: ['Macro', '\\mathbf{i}'],
      bfj: ['Macro', '\\mathbf{j}'],
      bfk: ['Macro', '\\mathbf{k}'],
      bfl: ['Macro', '\\mathbf{l}'],
      bfm: ['Macro', '\\mathbf{m}'],
      bfn: ['Macro', '\\mathbf{n}'],
      bfo: ['Macro', '\\mathbf{o}'],
      bfp: ['Macro', '\\mathbf{p}'],
      bfq: ['Macro', '\\mathbf{q}'],
      bfr: ['Macro', '\\mathbf{r}'],
      bfs: ['Macro', '\\mathbf{s}'],
      bft: ['Macro', '\\mathbf{t}'],
      bfu: ['Macro', '\\mathbf{u}'],
      bfv: ['Macro', '\\mathbf{v}'],
      bfw: ['Macro', '\\mathbf{w}'],
      bfx: ['Macro', '\\mathbf{x}'],
      bfy: ['Macro', '\\mathbf{y}'],
      bfz: ['Macro', '\\mathbf{z}'],
      bbA: ['Macro', '\\mathbb{A}'],
      bbB: ['Macro', '\\mathbb{B}'],
      bbC: ['Macro', '\\mathbb{C}'],
      bbD: ['Macro', '\\mathbb{D}'],
      bbE: ['Macro', '\\mathbb{E}'],
      bbF: ['Macro', '\\mathbb{F}'],
      bbG: ['Macro', '\\mathbb{G}'],
      bbH: ['Macro', '\\mathbb{H}'],
      bbI: ['Macro', '\\mathbb{I}'],
      bbJ: ['Macro', '\\mathbb{J}'],
      bbK: ['Macro', '\\mathbb{K}'],
      bbL: ['Macro', '\\mathbb{L}'],
      bbM: ['Macro', '\\mathbb{M}'],
      bbN: ['Macro', '\\mathbb{N}'],
      bbO: ['Macro', '\\mathbb{O}'],
      bbP: ['Macro', '\\mathbb{P}'],
      bbQ: ['Macro', '\\mathbb{Q}'],
      bbR: ['Macro', '\\mathbb{R}'],
      bbS: ['Macro', '\\mathbb{S}'],
      bbT: ['Macro', '\\mathbb{T}'],
      bbU: ['Macro', '\\mathbb{U}'],
      bbV: ['Macro', '\\mathbb{V}'],
      bbW: ['Macro', '\\mathbb{W}'],
      bbX: ['Macro', '\\mathbb{X}'],
      bbY: ['Macro', '\\mathbb{Y}'],
      bbZ: ['Macro', '\\mathbb{Z}'],
      T: ['Macro', '\\mathsf{T}'],
      R: ['Macro', '\\mathbb{R}'],
      KL: ['Macro', 'D_{\\mathrm{KL}}'],
      E: ['Macro', '\\mathop{\\mathbb{E}}'],
      p: ['Macro', '\\mathbb{P}'],
      Var: ['Macro', '\\mathrm{Var}'],
      sgn: ['Macro', '\\mathrm{sgn}'],
      diag: ['Macro', '\\mathrm{diag}'],
      poly: ['Macro', '\\mathrm{poly}'],
      1: ['Macro', '\\mathbf{1}'],
      eps: ['Macro', '\\varepsilon'],
    }
  })
})

MathJax.Ajax.loadComplete('[MathJax]/extensions/custom.js')

