[buildPlans.iosevka-drd]                         # <iosevka-custom> is your plan name
family = "Iosevka DRD"                           # Font menu family name
spacing = "normal"

[buildPlans.iosevka-drd.variants.design]
g = 'double-storey'
# i = 'zshaped'
# ll = 'zshaped'
four = 'semi-open'
six = 'open-contour'
nine = 'open-contour'
asterisk = 'hex-low'
brace = "curly"
at = 'fourfold'
underscore = 'high'
number-sign = 'slanted'
percent = "rings-continuous-slash"
lig-ltgteq = 'slanted'

[buildPlans.iosevka-drd.variants.italic]
b = "toothless-corner-serifless"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
i = "tailed-serifed"
j = "serifed"
k = "cursive-serifless"
l = "tailed-serifed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"


# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
[buildPlans.iosevka-drd.weights.regular]
shape = 400                            # Weight for glyph shapes
menu  = 400                            # Weight for menu name
css   = 400                            # Weight for webfont CSS

# [buildPlans.iosevka-drdx.weights.medium]
# shape = 500                            # Weight for glyph shapes
# menu  = 500                            # Weight for menu name
# css   = 500                            # Weight for webfont CSS

[buildPlans.iosevka-drd.weights.bold]
shape = 700
menu  = 700
css   = 700
# end weight section


# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-drd.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-drd.slopes.upright]
angle = 0             # Angle in degrees. Valid range [0, 15]
shape = "upright"     # Slope grade used for shape selection.  `upright` | `oblique` | `italic`
menu  = "upright"     # Slope grade used for naming.           `upright` | `oblique` | `italic`
css   = "normal"      # Slope grade used for webfont CSS.      `normal`  | `oblique` | `italic`

